Delete bash array, loop directly over the files

diff --git a/gu-e2t b/gu-e2t
--- a/gu-e2t
+++ b/gu-e2t
@@ -15,10 +15,10 @@ EOF
 	exit 1
 }
 
+# no args supplied
 if [ -z $1 ]; then
 	usage
 fi
-
 
 le() {
 	# returns $1 <= $2 lexicographically
@@ -48,22 +48,6 @@ done
 # shift args
 shift $((OPTIND - 1))
 
-
-files=()
-for file in "$@"
-do
-	if [[ "$file" != *.pdf ]]; then
-		echo "Skipping '$file' : Not a .pdf file" >&2;
-	else 
-		files+=("$file")
-	fi
-done
-
-if [ ${#files[@]} -eq 0 ]; then
-    echo "No valid PDF files provided." >&2
-    exit 1
-fi
-
 # temporary build dir
 BUILD_DIR=$(mktemp -d)
 TMP_TEXT="$BUILD_DIR/tmp_text"
@@ -73,23 +57,33 @@ USER_COURSES="$BUILD_DIR/user-courses"
 OUTPUT_TSV="$BUILD_DIR/output.tsv"
 TEX_COMPILE="$BUILD_DIR/table.tex"
 
-
-for pdf in "${files[@]}"; do
-    echo "Processing $pdf..."
-    # Use "$pdf", not "$file"
-    if pdftotext -layout -nopgbrk "$pdf" "$TMP_TEXT"; then
-        # delete bloat and append
-        sed -i '1,/Exam Code/d' "$TMP_TEXT"
-        cat "$TMP_TEXT" >> "$PDF_TEXT"
-    else
-        echo "Error: Could not process $pdf" >&2
-    fi
-done
-
 # temp file access just for us + trap to delete
 umask 077
 trap "exit 1"					HUP INT PIPE QUIT TERM
 trap "rm -rf $BUILD_DIR"		EXIT
+
+# no files supplied
+if [ -z "$1" ]; then
+	usage
+fi
+
+for file in "$@"; do
+	case "$file" in 
+		*.pdf)
+			echo "Processing $file..."
+			if pdftotext -layout -nopgbrk "$file" "$TMP_TEXT"; then
+				# delete bloat and append
+				sed -i '1,/Exam Code/d' "$TMP_TEXT"
+				cat "$TMP_TEXT" >> "$PDF_TEXT"
+			else
+				echo "Error: Could not process $pdf" >&2
+			fi
+			;;
+		*)
+			echo "Skipping $file, not a pdf file..." >&2
+			;;
+	esac
+done
 
 # delete empty lines
 sed -i '/^$/d' "$PDF_TEXT"
